# ==========================================
# Configuração do PostgreSQL (Dinâmico para Render / Local)
# ==========================================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vitrine_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# ==========================================
# Configurações do Hibernate (JPA)
# ==========================================
# Isso diz ao Java para criar a tabela de produtos automaticamente no Postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Mantendo a porta aberta para o WSL (caso precise)
server.address=0.0.0.0